# Generated by Django 3.2.5 on 2021-08-11 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_village', '0003_auto_20210811_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='villagenews',
            old_name='text_of_title',
            new_name='text_of_news',
        ),
    ]
