# Generated by Django 3.2.5 on 2021-08-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_village', '0004_rename_text_of_title_villagenews_text_of_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villagenews',
            name='short_text_of_news',
            field=models.TextField(default='Краткое описание', max_length=100, verbose_name='Краткое описание'),
        ),
    ]
