# Generated by Django 3.2.5 on 2021-08-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_village', '0006_auto_20210811_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villagenews',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
