# Generated by Django 3.2.5 on 2021-08-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_village', '0007_alter_villagenews_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villagenews',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
