# Generated by Django 3.2.5 on 2021-08-12 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0011_delete_villagepictures'),
        ('main_village', '0008_alter_villagenews_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillageChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_of_comment', models.TextField(verbose_name='Содержимое комментария')),
                ('date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, default='Некий пользователь', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('village_name', models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.village_data')),
            ],
            options={
                'verbose_name': 'Чат населённого пункта',
                'ordering': ['village_name__title'],
            },
        ),
    ]
