# Generated by Django 3.2.5 on 2021-08-12 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_village', '0009_villagechart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='villagechart',
            options={'ordering': ['date'], 'verbose_name': 'Чат населённого пункта'},
        ),
        migrations.RenameField(
            model_name='villagechart',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='villagechart',
            old_name='village_name',
            new_name='village_id',
        ),
    ]
