# Generated by Django 3.2.5 on 2021-07-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='layout_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('main_consistion', models.TextField(verbose_name='Содержимое')),
                ('data', models.JSONField()),
            ],
        ),
    ]
