# Generated by Django 3.2.5 on 2021-07-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='village_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название населнённого пункта')),
                ('short_information', models.TextField(verbose_name='Краткое описание')),
                ('village_avatar_link', models.CharField(max_length=300, verbose_name='Ссылка на аватак')),
            ],
        ),
    ]
