# Generated by Django 3.2.5 on 2021-08-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_village_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout_data',
            name='main_consistion_2',
            field=models.TextField(default='', null=True, verbose_name='Содержимое ниже фото'),
        ),
        migrations.AlterField(
            model_name='layout_data',
            name='main_consistion',
            field=models.TextField(verbose_name='Содержимое выше фото'),
        ),
        migrations.AlterField(
            model_name='village_data',
            name='village_avatar_link',
            field=models.CharField(max_length=300, verbose_name='Ссылка на аватар'),
        ),
    ]
