# Generated by Django 3.2.5 on 2021-08-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20210803_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='village_data',
            name='all_information',
            field=models.TextField(blank=True, verbose_name='Подробная информация'),
        ),
        migrations.AddField(
            model_name='village_data',
            name='at_the_moment',
            field=models.TextField(blank=True, verbose_name='Ситуация на данный момент'),
        ),
        migrations.AddField(
            model_name='village_data',
            name='historical_informaion',
            field=models.TextField(blank=True, verbose_name='Историческая справка'),
        ),
        migrations.AddField(
            model_name='village_data',
            name='possibilities',
            field=models.TextField(blank=True, verbose_name='Возможности для предпринимателей'),
        ),
    ]
