# Generated by Django 3.2.5 on 2021-08-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_villagepictures_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layout_data',
            options={'ordering': ['title'], 'verbose_name': 'Данные для статических страниц'},
        ),
        migrations.AlterModelOptions(
            name='regions',
            options={'ordering': ['name'], 'verbose_name': 'Регионы'},
        ),
        migrations.AlterModelOptions(
            name='village_data',
            options={'ordering': ['region'], 'verbose_name': 'Данные о деревнях'},
        ),
    ]
