# Generated by Django 3.2.5 on 2021-08-11 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20210809_1143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VillagePictures',
        ),
    ]
